// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package hr.tvz.java.godisnjak.entity;

import hr.tvz.java.godisnjak.entity.AcademicYear;

privileged aspect AcademicYear_Roo_JavaBean {
    
    public String AcademicYear.getName() {
        return this.name;
    }
    
    public void AcademicYear.setName(String name) {
        this.name = name;
    }
    
}
