// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package hr.tvz.java.godisnjak.entity;

import hr.tvz.java.godisnjak.entity.ApplicationUserType;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ApplicationUserType_Roo_Configurable {
    
    declare @type: ApplicationUserType: @Configurable;
    
}
